### ISSUE TITLE
Copyright string must be ascii

### ISSUE THREAD

**Issue by davelab6** [rosettatype/yrsa-rasa#1]
Your copyright strings are non-ascii, eg

```
    <string>Copyright © 2016 by Rosetta Type Foundry. All rights reserved.</string>
```

https://github.com/rosettatype/yrsa/blob/master/Production/UFOs/Rasa-Light.ufo/fontinfo.plist#L10

I suggest that, similar to 

```
Copyright (c) 2014, Vaibhav Singh (design) and Rosetta Type Foundry s.r.o. (post-production).
```

https://github.com/rosettatype/eczar/blob/master/Design/Eczar-Bold.glyphs#L37

We change it to

```
    <string>Copyright (c) 20XX Rosetta Type Foundry (info@rosettatype.com)</string>
```

where the year is the first year you started working on it.

**Comment by MrBrezina** [comment]
Ah. this gets changed in AFDKO anyway, but I will update it the way you like it.

**Comment by davelab6** [comment]
You mean FDK will remove the nonascii char?

**Comment by MrBrezina** [comment]
I mean that there are name table overrides in the AFDKO [feature files](https://github.com/rosettatype/yrsa/blob/master/Production/Yrsa/uprights.tables.fea). I rewrite most of the font info there, this was just a leftover from Glüphs.
