### ISSUE TITLE
Yrsa 'i' not rendered in MSIE 11

### ISSUE THREAD

**Issue by davelab6** [rosettatype/yrsa-rasa#11]
> <img width="485" alt="screen shot 2017-09-18 at 15 46 05" src="https://user-images.githubusercontent.com/261579/30561284-808e2bda-9c88-11e7-8ad5-b1e975a92a3e.png">
>
> - https://twitter.com/PrestonStahley/status/906223732661911553

**Comment by laerm0** [comment]
I was able to reproduce this, but only in the newest version of IE: all other browsers work fine.

I'm digging in further. I did notice that VTT throws an error about the maxp being off, so it might be as simple as a recalc of that.

**Comment by majorosgereby** [comment]
I had this problem again, when I have tried to create a PDF from DOCX in MS Word.
lowercase i and j disappeared, but upparcase not. 
also accents/diacritics (all that is used in Hungarian text) completly disappeared in both lowercase and uppercase text.
![yrsa betűhiba](https://user-images.githubusercontent.com/25921022/56893966-b23bc680-6a84-11e9-9362-b96e040e3a35.png)

**Comment by kontur** [comment]
![VirtualBox_IE11 - Win81_08_11_2021_10_49_35](https://user-images.githubusercontent.com/1893577/140720460-403b7437-f1cd-45ad-b4d2-49767416b286.png)

Testing with the current GF hosted version this appears fixed, so closing this issue.
