### ISSUE TITLE
Dutch "ij" rendered incorrectly on Firefox in Linux

### ISSUE THREAD

**Issue by Thomas-N** [rosettatype/yrsa-rasa#12]
The Dutch "ij" only gets one letter worth of space, but takes up two letters worth of space. The result is that the next character slightly overlaps the preceding "ij".

For example, several occurences in the lead of this article: https://www.hpdetijd.nl/2018-08-23/onduidelijkheid-han-ten-broeke/

All Dutch-language websites using the Yrsa font seem to show this problem, leading me to believe it's a problem with Yrsa

**Comment by MrBrezina** [comment]
Have you identified the problem in the latest version? I believe it has been fixed.

**Comment by Thomas-N** [comment]
Thanks for your reply! I identified the problem on a couple of news websites that are not under my control. Is there an easy way to find out if they're using the latest version? They seem to be getting the fonts through Google's "fonts.googleapis.com". I'd expect that to be the latest version.

**Comment by MrBrezina** [comment]
Yeah. Me too. Download the fonts from here and see if they perform better. I really think they do. If not, we will fix it of course.

**Comment by Thomas-N** [comment]
Downloading and using the latest version fixes the problem. Thanks! That probably does mean the Google version is outdated. Any idea if they will update by themselves, or do they need some sort of reminder?

**Comment by MrBrezina** [comment]
Hey @davelab6 can you do something about it? We have fixed this a long time ago.
