### ISSUE TITLE
Yrsa webfonts: German ß sometimes renders as f

### ISSUE THREAD

**Issue by acrylian** [rosettatype/yrsa-rasa#24]
It seems - tested with the standard webfonts - creates an unwanted `ft` ligature if an `t` is followed. 

Example: If you write `heißt` it displays incorrectly as `heift`. To avoid this you have to use  `font-variant-ligatures: no-common-ligatures` in CSS to disable ligatures.

**Comment by kontur** [comment]
Thanks for reporting this, clearly a bug in the feature code! You can find updated files in the `/fonts` directory of this repo.

**Comment by acrylian** [comment]
Thanks for fixing it and of course making this font in the first place!
