### ISSUE TITLE
Lining "9" is off the baseline

### ISSUE THREAD

**Issue by ortoslon** [rosettatype/yrsa-rasa#26]
The lining "9" is above or below the baseline at some sizes.

https://github.com/rosettatype/yrsa-rasa/blob/1f2caa8a5eb98ba087963e0cbf25c13b5816687b/fonts/Yrsa/Yrsa-Regular.ttf in Chrome 95 on Win10:
![image](https://user-images.githubusercontent.com/79928123/139827892-4e19a3aa-4ce3-4af3-a35e-8c472419df77.png)

**Comment by kontur** [comment]
Thanks @ortoslon for reporting. We'll have a look at this with the next release.

**Comment by kontur** [comment]
Hey @ortoslon  it may take a while before the change comes live to the Google Fonts version of the fonts, but the binaries in the latest release should have a fix for this issue. Thanks again for bringing our attention to this.
