### ISSUE TITLE
Yrsa: 'frac' with wrong numbers

### ISSUE THREAD

**Issue by xm-casanova** [rosettatype/yrsa-rasa#27]
It seems there's a problem with OTF 'frac' feature (Yrsa version 2.002) as numbers are modified (e.g. 1234567890 → 2345678901).

Example in LibreOffice:
- 12345/12345 with 'Yrsa' font
- the same text using 'Yrsa:frac'

![yrsa frac](https://user-images.githubusercontent.com/38875524/140414499-fe2923b6-0fdc-4884-8672-5597a7453566.jpg)

**Comment by kontur** [comment]
Thanks @m-casanova for reporting, this looks like a typo/error in the opentype code. We'll take a look at this with the next release.

**Comment by kontur** [comment]
Hey @m-casanova, it may take a while before the change comes live to the Google Fonts version of the fonts, but the binaries in the latest release should have a fix for this issue. Thanks again for bringing our attention to this.
