### ISSUE TITLE
Yrsa version 2.004 missing from assets

### ISSUE THREAD

**Issue by usethetics** [rosettatype/yrsa-rasa#29]
Yrsa v2.004 version seems to be missing from assets. Instead the 2.004 version of Rasa seems to be listed twice.

![image](https://user-images.githubusercontent.com/248921/141974394-84c55e4c-7b3c-4992-954e-f90d5792e751.png)

**Comment by kontur** [comment]
Thanks for reporting, fixed now and you should find the Yrsa package from the release.
