### ISSUE TITLE
ETA on Google Fonts approval?

### ISSUE THREAD

**Issue by doot0** [rosettatype/yrsa-rasa#9]
Hey. I'm currently using Google Fonts to serve fonts in a few large scale applications and would rather avoid having to serve up Rasa via @font-face if I can help it. 

As per title, do you have an ETA on Google Fonts adding Rasa et al to their fonts repo?

Thanks.

**Comment by MrBrezina** [comment]
I have no idea. @davelab6 should know more.

**Comment by davelab6** [comment]
Early July

**Comment by doot0** [comment]
@davelab6 @MrBrezina Thanks for the reply. Will close now.
